---
# handlers file for setup-ocp-deployer
- name: Restart firewalld.service
  service:
    name: firewalld.service
    state: restarted
  listen: "restart firewalld"

- name: Restart chronyd.service
  service:
    name: chronyd.service
    state: restarted
  listen: "restart chronyd"

- name: Enable incrond service
  systemd:
    name: incrond
    state: stopped
    enabled: yes
  listen: "enable incrond"
