# Run the setup effort to build an OCP Bastion guest
- name: Create guest for OCP Bastion
  hosts: 127.0.0.1
  connection: local
  vars:
  - directory_entry: "{{ lookup('template', 'guest.direct.j2') }}"
  roles:
  - create-guest-for-linux
