---
- name: generate Apps private key
  openssl_privatekey:
    path: /etc/pki/tls/private/ocpApps.pem

- name: generate Apps CSR
  openssl_csr:
    path: /etc/pki/tls/misc/ocpApps.csr
    privatekey_path: /etc/pki/tls/private/ocpApps.pem
    common_name: "*.apps.{{ cluster_name }}.{{ cluster_base_domain }}"
    organization_name: "{{ cert_organization }}"
    organizational_unit_name: "Red Hat Openshift on LinuxONE PoC"
    country_name: "{{ cert_country }}"
    keyUsage: ["digitalSignature","keyAgreement"]
    extendedKeyUsage: ["clientAuth","serverAuth"]

- name: generate Certificate
  openssl_certificate:
    path: /etc/pki/tls/certs/ocpApps.cert
    csr_path: /etc/pki/tls/misc/ocpApps.csr
    ownca_path: /etc/pki/tls/certs/oqsCA.cert
    ownca_privatekey_path: /etc/pki/tls/private/oqsCA.pem
    ownca_not_after: +365d
    provider: ownca

- name: Generate PKCS12 file
  openssl_pkcs12:
    action: export
    path: /etc/pki/tls/certs/ocpApps.p12
    friendly_name: OCPAPPS
    privatekey_path: /etc/pki/tls/private/ocpApps.pem
    certificate_path: /etc/pki/tls/certs/ocpApps.cert
    other_certificates: /etc/pki/tls/certs/oqsCA.cert
    passphrase: zvm4demo
    state: present

- name: create combined PEM file for OCP apps
  shell:
    cmd: cat ocpApps.cert oqsCA.cert oqsRootCA.cert > ocpApps-bundle.cert
    chdir: /etc/pki/tls/certs

- name: Create OCP ConfigMap for CA certs
  command:
    cmd: oc create configmap custom-ca --from-file=ca.crt=/etc/pki/tls/certs/oqsCA.certs.bundle -n openshift-config

- name: Add OCP ConfigMap for CA cert
  command:
    cmd: |
      oc patch proxy/cluster --type=merge -p '{"spec":{"trustedCA":{"name":"custom-ca"}}}'

- name: Create OCP secret for the certificate and chain
  command:
    cmd: oc create secret tls oqscert --cert=/etc/pki/tls/certs/ocpApps-bundle.cert --key=/etc/pki/tls/private/ocpApps.pem -n openshift-ingress

- name: Update the Ingress Controller
  command:
    cmd: |
      oc patch ingresscontroller.operator default --type=merge -p '{"spec":{"defaultCertificate": {"name": "oqscert"}}}' -n openshift-ingress-operator

- name: Create the Custom Resource for the LDAP identity provider
  template:
    src: ldapIdentityCr.yml.j2
    dest: "{{ workdir }}/ldapIdentityCr.yml"

- name: Add the identity provider
  command:
    cmd: oc apply -f {{ workdir }}/ldapIdentityCr.yml

