name: AnsibleLint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint Ansible Playbooks
      uses: ansible/ansible-lint-action@master
      with:
        override-deps: |
          ansible==2.9.10
          ansible-lint==4.1.0
        targets: |
          local-playbooks/build-a-bastion.yml
          local-playbooks/create-cluster.yml
          local-playbooks/create-guest-for-linux.yml
          local-playbooks/create-root-ca.yml
          local-playbooks/create-zvm-certificates.yml
